### PR TITLE
Stick hero: optimized sleep time, setting control line based on screen height

### PR DESCRIPTION
**Pull request by ajkost**
tested till score 300 without any problems.

### CODE REVIEW

**Comment by NawafBajwa** [comment]
He told not to open a pull, code should remain the same.

**Comment by JarnoXYZ** [comment]
Actually, at the end of the video, he said that you could do it.
https://youtu.be/Du__JfXqsAs

**Comment by NawafBajwa** [comment]
Appreciate your work man, but the About section seems to be the latest one and asks users not to open a pull.

**Comment by ajkost** [comment]
Ok, np ;)

**Comment by realtux** [comment]
i'm definitely interested in seeing the improvements people have, but, the official version from the video has to remain the same in this repo as to not cause confusion for future viewers.

**Pull request closed without merging**
