### PR TITLE
Create ht_destroy routine to properly free up memory. Added call to m…

### PR DESCRIPTION
**Pull request by itsallmathematics**
Hi Engineer Man. I really enjoyed this tutorial and learned a lot. Unfortunately, there were 23 memory leaks in the code! I wrote a new `ht_destroy` function and added it to the end of `main` to fix these.I verified with Valgrind (see screenshot which has before and after) that these leaks are now gone.
hashtable_leaks . It's always a good practice to FREE all memory used because otherwise the program could crash or have a vulnerability.

Sincerely,
itsallmathematics

### CODE REVIEW

**Comment by realtux** [comment]
For your knowledge and for anybody who may read this, a memory leak is not memory that is not free'd. A memory leak is memory that you no longer have a reference to and are now unable to free.

In the case of this program, memory is free'd upon termination of the program.

The 160,249 bytes in 22 blocks isn't a memory leak. However, that 8 bytes in 1 block is interesting. I wonder what that is referring to.

**Comment by itsallmathematics** [comment]
@realtux Let's address that 1 block as you stated:

The real issue here is that the `entries` member of the `hashtable` provides no interface to be freed. The interface provided allows the consumer to free the `entry`, `key`, and `value` memory. The interface _does not_ provide a way to free the `ht_t` pointer, but that's ok because the caller can do that. I modified the program to call `ht_del` on every single key in the table (all 7 in this case), I then manually freed the `ht_t* hashtable` pointer that we create in `main`. The only remaining leak, clearly identified by AddressSanitizer, is indeed the direct leak which refers to line55 of `ht_create` as shown in the screenshot. Line 55 of `ht_create` is:

```
hashtable->entries = malloc(sizeof(entry_t*) * TABLE_SIZE);
```

The interface provides a way to create a hashtable, create entries, and remove entries, but it provides no way to free this `entries` member, and thus its a memory leak.

It's debatable what to call the others, but AddressSanitizer and the industry standard Unix Valgrind refers to them as leaks. Additionally, Wikipedia provides these two definitions:

```
In computer science, a memory leak is a type of resource leak that occurs when a computer program incorrectly manages memory allocations[1] in such a way that memory which is no longer needed is not released. A memory leak may also happen when an object is stored in memory but cannot be accessed by the running code.[2] 
```
In this PR, I use the first definition. I have no interest in going back and forth about terminology, but wanted to try and contribute to this as best I could, if nothing else, to also provide a convenient function to clean up the hashtable. I enjoy your tutorials and am an avid viewer.

Thanks,
itsallmathematics.

Code of what I did before I ran AddressSanitizer:

```
int main(int argc, char **argv) {
    ht_t *ht = ht_create();

    ht_set(ht, "name1", "em");
    ht_set(ht, "name2", "russian");
    ht_set(ht, "name3", "pizza");
    ht_set(ht, "name4", "doge");
    ht_set(ht, "name5", "pyro");
    ht_set(ht, "name6", "joost");
    ht_set(ht, "name7", "kalix");

    ht_dump(ht);
    ht_del(ht, "name1");
    ht_del(ht, "name2");
    ht_del(ht, "name3");
    ht_del(ht, "name4");
    ht_del(ht, "name5");
    ht_del(ht, "name6");
    ht_del(ht, "name7");

    free(ht);
    return 0;
}
![ht_leak_entries](https://user-images.githubusercontent.com/57550024/70383883-893cb780-192a-11ea-9d15-ab4d9e56e3ea.png)

```

**Comment by realtux** [comment]
Respectfully, terminology matters. But, as requested, we won't go back and forth over that.

I concur with that output at the bottom of your comment though. There is, in fact, a memory leak now and it was introduced by calling `free(ht);`. By calling that, `free(ht->entries);` because UB instead of a proper free. Insert `free(ht->entries);` right above `free(ht);` and I bet it won't complain anymore.

**Comment by itsallmathematics** [comment]
@realtux maybe we should remove `ht_create()` and just have the user manually set up the entire hashtable then, by that logic.

**Comment by speedrun-program** [comment]
The ht_destroy function doesn't free all the key-value pairs for slots with more than one pair. Here's what I changed it to to fix that:
```c
void ht_destroy(ht_t *hashtable)
{
    if(!hashtable) return;
    size_t i = 0;
    if(hashtable->entries)
    {
        //Free all entries
        entry_t *current_entry;
        while(i < TABLE_SIZE)
        {
            entry_t *entry = hashtable->entries[i];
            for (;;) {
                if(entry == NULL) {
                    break;
                }
                if(entry->key)
                {
                    free(entry->key);
                    entry->key = NULL;
                }
                if(entry->value)
                {
                    free(entry->value);
                    entry->value = NULL;
                }
                current_entry = entry;
                entry = entry->next;
                free(current_entry);
            }
            i++;
        }
        //Free the entry list pointer
        free(hashtable->entries);
        hashtable->entries = NULL;
    }
 
    //Free the hashtable pointer
    free(hashtable);
    hashtable = NULL;
    return;
}
```

**Pull request closed without merging**
